server:
  host: 127.0.0.1
  port: 80
database:
  host: "127.0.0.1"
  port: 3306
  name: "forgottenserver"
  user: "root"
  password: ""
worlds:
  - id: 0
    name: "Localhost"
    ip: "127.0.0.1"
    port: 7171
    location: "EUR"
    pvp-type: 0
